package de.upteams.tasktracker.task.utils;

import de.upteams.tasktracker.task.dto.TaskDto;
import de.upteams.tasktracker.task.entity.Task;
import de.upteams.tasktracker.user.util.AppUserMapper;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

/**
 * Interface for Task Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        uses = AppUserMapper.class
)
public interface TaskMappingService {

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "project.owner", ignore = true)
    @Mapping(target = "executors", ignore = true)
    TaskDto mapEntityToDto(Task entity);

    @Mapping(target = "project", ignore = true)
    @Mapping(target = "executors", ignore = true)
    Task mapDtoToEntity(TaskDto dto);
}
