package de.upteams.tasktracker.user.util;

import de.upteams.tasktracker.user.dto.response.UserResponseDto;
import de.upteams.tasktracker.user.entity.AppUser;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;

/**
 * Interface for Employee Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING
)
public interface AppUserMapper {

    UserResponseDto mapEntityToDto(AppUser entity);
}
